// angular/goramp-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'goramp-angular';
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 8px 0;
  }

  p {
    margin: 0;
  }

  .content {
    display: flex;
    margin: 82px auto 32px;
    padding: 0 16px;
    max-width: 960px;
    flex-direction: column;
    align-items: center;
  }

  .app {
    text-align: center;
  }

  .app-header {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: calc(10px + 2vmin);
    color: white;
  }

  .img-logo {
    width: 200px;
  }

  .link-tutorial {
    color: #61dafb;
    font-size: 16px;
    margin-top: 16px;
    max-width: 400px;
    margin-bottom: 16px;
  }

  .ramp-btn {
    border: none;
    color: white;
    background-color: #282c34;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }
</style>

<div class="app" role="main">
  <header class="app-header">
    <img src="https://goblockchain.io/wp-content/uploads/2023/07/logo-goblockchain.svg" class="img-logo" alt="logo" />
    <a class="link-tutorial" href="https://doc.clickup.com/9004111187/p/h/8caznak-6653/85ada0df2ea13c9" target="_blank"
      rel="noopener noreferrer">
      Tutorial: integração com GoRamp em apenas 3 linhas de código
    </a>
    <goramp-button publicKey="fb80f3e5d8e8b412d447b1908b6dd9f115eecc9be53ec97e">
      <button class="ramp-btn">
        GoRamp
      </button>
    </goramp-button>
  </header>
</div>

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<router-outlet></router-outlet>

// react/myway-app-typescript/src/App.tsx
import React from "react";
import "./App.css";

// NOTE: the typing below is needed only when using Typescript
declare global {
  namespace JSX {
    interface IntrinsicElements {
      "goramp-button": {
        publicKey: string;
        paymentId?: string;
        amount?: string | number;
        baseCurrency?: string;
        network?: string;
        paymentMethod?: string;
        redirectUrl?: string;
        walletAddress?: string;
        frameWidth?: string | number;
        frameHeight?: string | number;
        frameZIndex?: string | number;
        children: React.ReactNode;
      };
    }
  }
}

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img
          src={
            "https://goblockchain.io/wp-content/uploads/2023/07/logo-goblockchain.svg"
          }
          style={{ width: "200px" }}
          alt="logo"
        />
        <a
          style={{
            color: "#61dafb",
            fontSize: 16,
            marginTop: 16,
            marginBottom: 16,
            maxWidth: 400,
          }}
          href="https://doc.clickup.com/9004111187/p/h/8caznak-6653/85ada0df2ea13c9"
          target="_blank"
          rel="noopener noreferrer"
        >
          Tutorial: integração com GoRamp em apenas 3 linhas de código
        </a>
        <goramp-button
          publicKey="fb80f3e5d8e8b412d447b1908b6dd9f115eecc9be53ec97e"
          paymentId="909e12ee-5281-11ee-863a-461660f348f1"
        >
          <button
            style={{
              border: "none",
              color: "white",
              backgroundColor: "#282c34",
              padding: "15px 32px",
              textAlign: "center",
              textDecoration: "none",
              display: "inline-block",
              fontSize: "16px",
              margin: "4px 2px",
              cursor: "pointer",
            }}
          >
            GoRamp
          </button>
        </goramp-button>
      </header>
    </div>
  );
}

export default App;
